# Numpy
Numpy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 중요한 패키지 중 하나이다. 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통언어처럼 사용되고 있음

## Numpy 라이브러리 import

In [1]:
import numpy as np

## Numpy ndarray
Numpy의 핵심 기능 중 하나는 ndarray라고 하는 N차원의 배열 객체인데 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료 구조임

In [2]:
a=np.array([1,2,3])
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


## list와 비교

In [3]:
L=[1,2,3]
A=np.array([1,2,3])
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [4]:
for item in L:
    print(item)

1
2
3


In [5]:
for item in A:
    print(item)

1
2
3


In [6]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [7]:
A=np.append(A,4)
print(A)

[1 2 3 4]


In [8]:
L=L+[5]
print(L)

[1, 2, 3, 4, 5]


In [10]:
A=A+np.array([5])#broad casting
print(A)

[6 7 8 9]


In [12]:
# list의 모든 원소를 2배로 만들기
L2=[]
for item in L:
    L2.append(item*2)
print(L2)

[2, 4, 6, 8, 10]


In [13]:
#ndarray의 모든 원소 2배로 만들기
A=np.array(L)
A2=A*2
print(A2)

[ 2  4  6  8 10]


In [14]:
L*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## 배열

numpy배열은 모두 같은 유형의 값이며 음수가 아닌 정슈의 튜플로 인덱싱이 됨.차원의 수는 배열의 랭크임. 배열의 shape는 각 차원별 배열 크기의 튜플임. 중첩 된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고 대괄호를 사용하여 요소에 접근할 수 잇음

### 배열 생성하기

In [15]:
a=np.array([1,2,3])
print(a)
print(type(a),a.ndim,a.shape,a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int32


In [16]:
b=np.asarray(a)
print(b)

[1 2 3]


In [18]:
b[0]=9 #a의 0인덱스 값도 바뀐다. => view
print(a,b)

[9 2 3] [9 2 3]


In [19]:
c=np.array(a)
print(c)

[9 2 3]


In [21]:
c[0]=1
print(a,b,c)

[9 2 3] [9 2 3] [1 2 3]


In [22]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
b=np.ones((5,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
c=np.full((2,3),4)
print(c)

[[4 4 4]
 [4 4 4]]


In [25]:
d=np.empty((3,3))
print(d)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.96433821e-321]
 [4.45057212e-308 8.90102880e-307 6.23020681e-307]]


In [28]:
e=np.zeros_like(a)#like가 붙으면 a의 shape만 가지고 오는 것
f=np.ones_like(a)
g=np.full_like(a,2)
h=np.empty_like(a)
print(e,f,g,h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]] [[1.23343872e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [7.56587583e-307 1.39403096e+165 3.60030257e+179 7.56677380e-067]
 [1.10791235e-047 8.75440188e+169 8.82930416e+169 2.63189997e-052]]


In [29]:
i=np.eye(3)#대각 행렬 생성
j=np.identity(3)
print(i,j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
k=np.arange(10)#0~9까지의 숫자가 채워짐
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
#1~10을 채우고 싶은 경우
k=np.arange(1,11)
print(k)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
k=np.arange(10,0,-1)#역순으로 출력
print(k)

[10  9  8  7  6  5  4  3  2  1]


In [34]:
#uniform distribution
l=np.random.rand(2,2)
print(l)

[[0.30066999 0.22745178]
 [0.04385662 0.29293367]]


In [36]:
#normal distribution
m=np.random.randn(2,2)
print(m)

[[ 0.54218711  1.51086869]
 [-0.05734997 -0.63645494]]


## 배열의 dtype

In [37]:
a=np.array([1,2,3])
b=np.array([1,2,3],dtype=np.float64)
c=np.array([1,2,3],dtype=np.int32)

print(a.dtype,b.dtype,c.dtype)

int32 float64 int32


In [39]:
#bite
d=np.array([1,2,3],dtype='i1')
e=np.array([1,2,3],dtype='i2')
f=np.array([1,2,3],dtype='i4')
g=np.array([1,2,3],dtype='i8')
print(d.dtype,e.dtype,f.dtype,g.dtype)

int8 int16 int32 int64


In [40]:
#unit
d=np.array([1,2,3],dtype='u1')
e=np.array([1,2,3],dtype='u2')
f=np.array([1,2,3],dtype='u4')
g=np.array([1,2,3],dtype='u8')
print(d.dtype,e.dtype,f.dtype,g.dtype)

uint8 uint16 uint32 uint64


In [44]:
#float :float 비트는 8비트가 없고 16비트부터 있음인데 해당 주피터 노트북은 .....뭐지?
d=np.array([1,2,3],dtype='f2')
e=np.array([1,2,3],dtype='f4')
f=np.array([1,2,3],dtype='f8')
g=np.array([1,2,3],dtype='f8')
print(d.dtype,e.dtype,f.dtype,g.dtype)

float16 float32 float64 float64


In [45]:
#float약자
d=np.array([1,2,3],dtype='f')
e=np.array([1,2,3],dtype='d')
f=np.array([1,2,3],dtype='g')
print(d.dtype,e.dtype,f.dtype)

float32 float64 float64


In [46]:
#타입을 변경하고 싶을 때
i=i.astype(np.int32)
print(i.dtype)

int32


In [48]:
e=e.astype(i.dtype)
print(e.dtype)

int32


# 배열 indexing(색인)과 slicing(슬라이싱)

## indexing, slicing 기본

In [49]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
#indexing
print(a[5])

5


In [51]:
#slicing
print(a[5:8])

[5 6 7]


In [52]:
print(a[-1])

9


In [53]:
print(a[7:-1])

[7 8]


In [54]:
a[5:8]=10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


## indexing 과 slicing의 차이
### indexing을 사용하면 항상 랭크가 감소함 반면에 slicing을 사용하면 차원이 유지됨

In [58]:
b=np.arange(1,13)
#b=b.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [59]:
indexing=b[1]
slicing=b[1:2]
print(indexing,indexing.shape,indexing.ndim)
print(slicing, slicing.shape,slicing.ndim)

2 () 0
[2] (1,) 1


이것은 indexing과 slicing을 함께 사용할 때도 마찬가지임. indexing의 개수만큼 랭크는 감소함

In [60]:
b=b.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [61]:
row_r1=b[1,:]
row_r2=b[1:2,:]
print(row_r1,row_r1.shape,row_r1.ndim)
print(row_r2,row_r2.shape,row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


## slicing examples

In [62]:
c=np.arange(24).reshape(2,3,4)
print(c)
print(c.shape)
print(c.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [63]:
print(c[:,:,:1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [66]:
print(c[0:1])
print(c[0::-1]) #

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


## boolean indexing

In [67]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [69]:
bool_index=(c>10)
print(bool_index)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [70]:
print(c[bool_index])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [71]:
c[c>10]=-1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


## fancy indexing

In [73]:
d=np.arange(8).reshape(8,-1)
print(d,d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [74]:
d=np.hstack((d,d,d,d))
print(d,d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [75]:
print(d[[3,5,1,0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [76]:
print(d[[-3,-5,-7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [78]:
e=np.arange(32).reshape(8,4)
print(e,e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [79]:
print(e[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [81]:
print(e[[1,5,7,2]][:,[0,3,1,2]]) #뒤에는 열 순서

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## Transpose

In [83]:
f=np.arange(16).reshape(2,2,4)
print(f,f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [84]:
print(f.transpose(1,0,2))#축의 위치를 바꿔라

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [86]:
print(f.swapaxes(0,1))#두개의 축만 순서를 바꾸는 경우

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


## Numpy연산

In [87]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [88]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [90]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [92]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [93]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [94]:
print(x@y)
print(np.matmul(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [98]:
z=np.arange(1,11).reshape(2,5)
print(z)
print(np.sum(z))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
55


In [99]:
sum1=np.sum(z,axis=0)
sum2=np.sum(z,axis=1)
sum3=np.sum(z,axis=-1)
print(sum1,sum1.shape)
print(sum2,sum2.shape)
print(sum3,sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


여기서 축(axis)는 각 배열의 창원에 해당되는 index임
axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 모두 원소를 더하라는 의미임
즉, 위의 예에서 sum1의 경우 z[0, : ]+z[1,:]의 연산을 하라는 의미이고,
sum2의 경우에는 z[:,0]+z[:,1]+z[:,2]+...+z[:4]를 연산하라는 의미임

In [100]:
print(z[0,:]+z[1,:])

[ 7  9 11 13 15]


In [101]:
print(z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4])

[15 40]


# Broadcasting
Broadcasting은 numpy가 산술 연산을 수행할 때 다른 모양의 배열로 작업할 수 있게 해주는 강력한 메커니즘임.
종종 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러번 사용하여 더 큰 배열에서 어떤 연산을 수행하기를 원할 때가 있음
예를들어 행렬의 각 행에 상수 벡터를 추가할려고 가정 했을 때 numpy에서는 다음과 같이 진행할 수 잇음

In [102]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=np.array([1,0,2])

In [103]:
print(x,x.shape)
print(y,y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 2] (3,)


In [105]:
z=x+y
print(z,z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


z=x=y는 broadcasting으로 인해 x가(4,3)이고 y가 (3,)임에도 작동을 함
이 행은 실제로 y가 (4,3)인 것처럼 작동을 함
각 행은 y의 사본이었고, 합계는 요소별로 수행되었음

두 개의 배열을 브로드 캐스팅하는 것은 다음 규칙을 따름

1.배열의 랭크가 같지 않으면 두 모양이 같은 길이 가 될 때까지 배열의 낮은 랭크쪽에 1을 붙임
2.두 배열은 차원에서 크기가 같거나 배열 중 하나의 창원에 크기가 1인 경우 차원에서 호환 가능하다고 함
3.배열은 모든 창원에서 호환되면 함께 broadcast될 수 있음
4.Broadcast 후 각 배열은 두개의 입력 배열의 요소 모양 최대개수와 동일한 모양을 가진 것처럼 동작함
5.한 배열의 크기가 1이고 다른 배ㅕㅇㄹ의 크기가 1보다 큰 차원에서 첫번째 배열은 마치 해당 차원을 따로 복사된 것처럼 작동함

실제로 동작하는 방식을 생각해봄

1. A와 B의 모양을 생각해보자
2. 두 배열이 len(A.shape)==len(B.shape)인지 확인을 함
3.같지 않은 경우에는 두 배열의 모양길이가 같아질 때까지 적은 쪽의 shape앞에 1을 추가해줌

예(5,3)->(1,5,3)

4. shape이 1인 곳은 복사가 됨

[shape의 변화는 아래와 같음]
- (5,3)+(3,)
-> (5,3)+(1,3)
-> (5,3)+(5,3)
-> (5,3)



In [106]:
x=np.array([1,2,3]).reshape(1,3)
y=np.array([4,5]).reshape(1,2)
print(x,x.shape)
print(y,y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [107]:
#broadcasting조건에 맞지않음(1번 조건은 만족, 2번조건 1열에서 만족x)
print(x+y)

ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

In [109]:
y=y.swapaxes(0,1)
print(y,y.shape)

[[4]
 [5]] (2, 1)


In [110]:
print(x+y)

[[5 6 7]
 [6 7 8]]


## Shape 변경

In [111]:
a=np.arange(24).reshape(2,3,4)
print(a,a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [112]:
a=a.reshape(4,-1)
print(a,a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [113]:
a=a[...,np.newaxis]#...== ;, ;
print(a,a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [114]:
a=a.reshape(4,6)
a=np.expand_dims(a,axis=0)
print(a,a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [115]:
b=a.copy()
print(b,b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [116]:
c=np.concatenate((a,b),axis=0)
print(c,c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [117]:
d=np.stack((a,b),axis=-1)
print(d,d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [118]:
d=np.stack((a,b),axis=0)
print(d,d.shape)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
